WebUI/Models/CartViewModel.cs
using Domain.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebUI.Models
{
    public class CartIndexViewModel
    {
        public Cart Cart { get; set; }
        public string ReturnUrl { get; set; }
    }
}

WebUI/Models/ItemListViewModel.cs
using Domain.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebUI.Models
{
    public class ItemListViewModel
    {
        public IEnumerable<item> items { get; set; }
        public PagingInfo PagingInfo { get; set; }
        public string CurrentType { get; set; }
        
    }
}

WebUI/Models/PagingInfo.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebUI.Models
{
    public class PagingInfo
    {
        public int TotalItems { get; set; }   //Общее кол-во товара
        public int ItemsPerPage { get; set; } //Кол-во товара на странице
        public int CurrentPage { get; set; }   //Номер текущей страницы
        public int TotalPages                 //Общее кол-во страниц
    {
        get {return(int)Math.Ceiling((decimal)TotalItems/ItemsPerPage);
    }
    }
    }
}

WebUI/Controllers/CartController.cs
using Domain.Abstract;
using Domain.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebUI.Models;

namespace WebUI.Controllers
{
    public class CartController : Controller
    {
        private IItemRepository repository;
        public CartController(IItemRepository repo)
        {
            repository = repo;
        }

        public ViewResult Index(Cart cart, string returnUrl)
        {
            return View(new CartIndexViewModel
            {
                Cart = cart,
                ReturnUrl = returnUrl
            });
        }

        //public RedirectToRouteResult AddToCart(Cart cart, int itemID, string returnUrl)
        //{
          //  item Item = repository.items
            //    .FirstOrDefault(b => b.itemId == itemID);

            //if (Item != null)
            //{
              //  cart.AddItem(Item, 1);
            //}

            //return RedirectToAction("Index", new { returnUrl });
        //}

        public RedirectToRouteResult RemoveFromCart(Cart cart, int ItemID, string returnUrl)
        {
            item Item = repository.items
                .FirstOrDefault(b => b.itemId == ItemID);

            if (Item != null)
            {
                cart.RemoveLine(Item);
            }

            return RedirectToAction("Index", new { returnUrl });
        }

        public PartialViewResult Summary(Cart cart)
        {
            return PartialView(cart);
        }

    }
}

WebUI/Controllers/ItemsController.cs
using Domain.Abstract;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebUI.Models;

namespace WebUI.Controllers
{
    public class ItemsController : Controller
    {
        private IItemRepository repository;
        public int pageSize = 3;

        public ItemsController(IItemRepository repo)

        {
            repository = repo;
        }

        public ViewResult List(string Type, int page = 1)
        {
            ItemListViewModel model = new ItemListViewModel
            {
                items = repository.items
                .Where(b => Type == null || b.type == Type)
                .OrderBy(item=>item.itemId)
                .Skip((page - 1) *pageSize)
                .Take(pageSize),
                PagingInfo = new PagingInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = pageSize,
                    TotalItems = Type == null ?
                    repository.items.Count() : 
                    repository.items.Where(items => items.type == Type).Count()
                },
                CurrentType=Type
            };

            return View(model);
        }
    }
}

WebUI/Controllers/NavController.cs
using Domain.Abstract;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebUI.Controllers
{
    public class NavController : Controller
    {
        private IItemRepository repository;

        public NavController(IItemRepository repo)
        {
            repository = repo;
        }

        public PartialViewResult Menu(string type = null)
        {
            ViewBag.SelectedType = type;

            IEnumerable<string> types = repository.items
                .Select(item => item.type)
                .Distinct()
                .OrderBy(x => x);

            return PartialView(types);
        }
    }
}

WebUI/Views/Cart/Index.cshtml
@model WebUI.Models.CartIndexViewModel

@{
    ViewBag.Title = "PetShop: Ваша корзина";
}

<style>
    #cartTable td {
        vertical-align: middle;
    }
</style>

<h2>@ViewBag.Title</h2>

<table id="cartTable" class="table">
    <thead>
        <tr>
            <th>Количество</th>
            <th>Наименование</th>
            <th class="text-right">Цена</th>
            <th class="text-right">Сумма</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var line in Model.Cart.Lines)
        {
            <tr>
                <td class="text-center">@line.Quantity</td>
                <td class="text-left">@line.item.name - @line.item.description</td>
                <td class="text-right">@line.item.price.ToString("# руб")</td>
                <td class="text-right">@((line.Quantity * line.item.price).ToString("# руб"))</td>
                <td>
                    @using (Html.BeginForm("RemoveFromCart", "Cart"))
                    {
                        @Html.Hidden("itemId", line.item.itemId)
                        @Html.HiddenFor(x => x.ReturnUrl)
                        <input class="btn btn-sm btn-warning" type="submit" value="Удалить" />
                    }
                </td>
            </tr>
        }
    </tbody>
    <tfoot>
        <tr>
            <td colspan="3" class="text-right">Итого:</td>
            <td class="text-right">
                @Model.Cart.ComputeTotalValue().ToString("# руб")
            </td>
        </tr>
    </tfoot>
</table>

<div class="text-center">
    <a class="btn btn-primary" href="@Model.ReturnUrl">Продолжить покупки</a>
</div>

WebUI/Views/Items/List.cshtml
@using WebUI.Models
@model ItemListViewModel

@{
    ViewBag.Title = "Товары";
}
<style>
    body { background: url(hello.png) }
    </style>

@foreach (var Item in Model.items)
{
   @Html.Partial("_ItemSummary", Item)

}
<div class="btn-group pull-right">
    @Html.PageLinks(Model.PagingInfo, x=> Url.Action("List", new { page = x, type = Model.CurrentType} ))
    </div>

WebUI/Views/Nav/Menu.cshtml
@model IEnumerable<string>

@Html.ActionLink("Домой", "List", "items", null, new { @class = "btn btn-block btn-default btn-lg" })

@foreach (var link in Model)
{
    @Html.RouteLink(link, new
{
    controller = "items",
    action = "List",
    type = link,
    page = 1
}, new
{
    @class = "btn btn-block btn-default btn-lg"
             + (link == ViewBag.SelectedType ? " btn-primary" : "")
})
}

WebUI/Views/Shared/_ItemSummary.cshtml
@model Domain.Entities.item

<div class="well">
    <div class="row">
        <div class="col-xs-10">
            <h3>
                <strong>@Model.name</strong>
            </h3>
          
        </div>
        <div class="col-xs-2">
            <h3>
                <strong id="price" class="pull-right label label-primary">
                    @Model.price.ToString("# руб")
                </strong>
            </h3>
            @using (Html.BeginForm("AddToCart", "Cart"))
            {
                <div class="pull-right">
                    @Html.HiddenFor(x => x.itemId)
                    @Html.Hidden("returnUrl", Request.Url.PathAndQuery)
                    <input type="submit" class="btn btn-success" value="Добавить в корзину" />
                </div>
            }
        </div>
    </div>
    <span class="lead">@Model.description</span>
</div>

WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/Site.css" rel="stylesheet" />
    <title>@ViewBag.Title - PetShop - магазин товаров для животных</title>
    <link href="~/Content/bootstrap-there.min.css" rel="stylesheet" />

</head>
<body>

    <div class="navbar navbar-inverse" role="navigation" >
<a class="navbar-brand"href="#">
PetShop - магазин товаров для животных
</a>

 </div>

    <div class="row panel">

        <div id="types" class="col-xs-3">
            @Html.Action("Menu","Nav")
        </div>
    
    <div class="col-xs-8">
        @RenderBody()


     
</div>

    </div>




</body>

</html>